image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test

before_script:
  - dotnet --version

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0-windowsservercore-ltsc2019
  tags: [windows]
  script:
    - dotnet build Robotok.Library


test:
  stage: test
  before_script:    
    - dotnet restore Robotok.Test --packages .nuget
  script:
    - dotnet test Robotok.Test --no-restore
  cache:
    key: "unittest-$CI_COMMIT_REF_SLUG"
    paths:
      - .nuget


