image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test

before_script:
  - dotnet --version

build_model:
  stage: build
  script:
    - dotnet build Robotok.Library

build_view:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0-windowsservercore-ltsc2019
  tags: [windows]
  script:
    - dotnet build Robotok



