image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test

before_script:
  - dotnet --version

build_model:
  stage: build
  script:
    - dotnet build Robotok.Library

test_model:
  stage: test
  before_script:    
    - dotnet restore Robotok.TestCases --packages .nuget
  script:
    - dotnet test Robotok.TestCases --no-restore




