image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test

before_script:
  - dotnet --version

build_model:
  stage: build

build_view:
  stage: build

test_model:
  stage: test

test_view:
  stage: test